#spring:
#  application:
#    name: gateway_service
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8089/
#          predicates:
#            - Path=/laboratory/**
#        - id: r2
#          uri: http://localhost:8088/
#          predicates:
#            - Path=/user/**
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      prefer-ip-address: true
#
#server:
#  port: 8888
